### ISSUE TITLE
self-critical training [duration and memory occupation]

### ISSUE THREAD

**Issue by nilinykh** [yahoo/object_relation_transformer#11]
Hej,

thank you a lot for your great work and some nice code!

I have a question regarding the self-criticial extra training. I am not exactly sure if there is an issue with it, but could you please tell me, how much memory self-critical training should consume?
I keep running into CUDA out of memory error with 3 GPUs, and I can see that self-critical training is really hungry for space...therefore, I wanted to hear from the authors of the paper how much space this extra training required in the original experiments? And was there any optimisation of the code to handle this issue?

Best,
Nikolai.

**Comment by simaoh** [comment]
Thanks Nikolai, 
On a single V100 GPU the extra 30 epochs of self-critical training should take 3.5 days.
I believe you shouldn't run into any memory error. 
Please let us know if this problem persists, or whether you were able to solve it.
